config/routes.rb
Rails.application.routes.draw do

  root 'overview#index'

  get 'summary' => 'summary#index'
  get 'history' => 'summary#history'

  resources :summary do
    member do
      get :thing
    end
  end

end

app/controllers/summary_controller.rb
class SummaryController < ApplicationController

  def index
    latest = Alert.find_latest
    @latest = latest.print
    @all = Alert.find_all
  end

  def thing
    @current_alert = Alert.find(params[:id])
    @tweets = @current_alert.get_tweets
    loc = Locator.new
    loc.get_json # loads the location data
    @top_locations, @map_locations = loc.find_matches(@tweets)
  end


  def history
    @true_alerts = "" #Alert.find_true
  end

end

app/helpers/summary_helper.rb
module SummaryHelper

  def display_alert(alert)
    css_class = "active_#{alert.active}"
    "<p class=\"#{css_class}\"> #{alert.print} </p>".html_safe
  end


  def display_text(string)
    string.split("~*~").inject(""){ |str, n| str + "<p>#{n}</p>".html_safe}.html_safe
  end

end

app/views/summary/history.html.erb
<h1>Hello</h1>
<!--%= @true_alerts %-->

app/views/summary/index.html.erb
<h3>Latest:</h3>
<p><%= @latest %></p>

<h3>All:</h3>
<% @all.each do |alert| %>
<%= link_to(thing_summary_path(alert),thing_summary_path(alert)) %>
<%= display_alert(alert) %>
<% end %>

app/views/summary/thing.html.erb
<%= display_alert(@current_alert) %>

<script src="http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.js"></script>
<div class="row">
  <div class="col-sm-12">
    <div id="map"></div>
  </div>
</div>

<p class="locations"><%= display_word_cloud(@top_locations) %></p>

<h3><%= @current_alert.issued_at %></h3>
<h3><%= @current_alert.tags %></h3>
<%= display_text(@current_alert.description) %>
<h3><%= @current_alert.threshold %></h3>

<script>
  //  var map = L.map('map').setView([-6.21, 106.85], 9);
  var map = L.map('map').setView([-2.0, 117.0], 5);
  L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
  attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
  maxZoom: 18,
  id: '<%= get_map_id %>',
  accessToken: '<%= get_map_token %>'
  }).addTo(map);

</script>


<% pairs = @map_locations.values %>
<% pairs.each do |pair| %>
<script>
  var circle = L.circle([<%=pair[0]%>, <%=pair[1]%>], <%=circle_radius(pair[2])%>, {
  color: '<%= circle_colour %>', fillColor: '<%= circle_fill_colour %>', fillOpacity: 0.5
  }).addTo(map);
</script>
<% end %>